// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO-BuP-exHZUYoFZCnQydJjcB4BOVEtjU',
    appId: '1:1031943572326:web:d7f3e3d4ee620d25fdd6a7',
    messagingSenderId: '1031943572326',
    projectId: 'background-editor-248d6',
    authDomain: 'background-editor-248d6.firebaseapp.com',
    storageBucket: 'background-editor-248d6.firebasestorage.app',
    measurementId: 'G-9SD3P3JTS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8nep8qsFX03-YIG7XVS5DPVCBTkSXaM',
    appId: '1:1031943572326:android:d0a8ab6a4b793375fdd6a7',
    messagingSenderId: '1031943572326',
    projectId: 'background-editor-248d6',
    storageBucket: 'background-editor-248d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKdfKRG8108HmK9MiRRvotY-nJQU2_I4',
    appId: '1:1031943572326:ios:512dfb3afb5f81ebfdd6a7',
    messagingSenderId: '1031943572326',
    projectId: 'background-editor-248d6',
    storageBucket: 'background-editor-248d6.firebasestorage.app',
    iosBundleId: 'com.example.mstProjectfoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKdfKRG8108HmK9MiRRvotY-nJQU2_I4',
    appId: '1:1031943572326:ios:512dfb3afb5f81ebfdd6a7',
    messagingSenderId: '1031943572326',
    projectId: 'background-editor-248d6',
    storageBucket: 'background-editor-248d6.firebasestorage.app',
    iosBundleId: 'com.example.mstProjectfoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO-BuP-exHZUYoFZCnQydJjcB4BOVEtjU',
    appId: '1:1031943572326:web:a199716fb2ee8fd1fdd6a7',
    messagingSenderId: '1031943572326',
    projectId: 'background-editor-248d6',
    authDomain: 'background-editor-248d6.firebaseapp.com',
    storageBucket: 'background-editor-248d6.firebasestorage.app',
    measurementId: 'G-GJNG906R01',
  );
}
